"""add updated_at to schedule_slots for crash recovery

Revision ID: 19dada1d8227
Revises: 969a88085965
Create Date: 2026-09-17 08:29:51.748549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19dada1d8227'
down_revision: Union[str, None] = '969a88085965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
