"""add updated_at to schedule_slots for crash recovery

Revision ID: 969a88085965
Revises: cef9434531d4
Create Date: 2026-09-17 08:25:02.352194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969a88085965'
down_revision: Union[str, None] = 'cef9434531d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_slots', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_slots', 'updated_at')
    # ### end Alembic commands ###
